### ISSUE TITLE
Materials tag in HTML is highlighted as error from Angular Language Service

### ISSUE THREAD

**Issue by yj91git** [microsoft/vs-ng-language-service#33] opened 2021-11-12 03:12 UTC
mat-slider tag is highlighted as error in HTML file: 
![image](https://user-images.githubusercontent.com/94154586/141402556-29d8ccaa-18dc-4322-89ba-5762a9b52ae9.png)

Imported MatSliderModule in AppModule:
![image](https://user-images.githubusercontent.com/94154586/141402617-ef362430-8bd7-4f94-ac3c-58ecd92ba272.png)

tsconfig.json
![image](https://user-images.githubusercontent.com/94154586/141404641-a8de94eb-1264-468f-909e-4e7c62f6bca9.png)

Using Angular 13.0.0 in VSCode version 1.62.1

**Comment by simo996** [comment] 2022-01-18 11:30
Hello. I'm experiencing the same issue even if I'm using a different component library (Ionic).
- VSCode version1.31.0
- Project built on Angular 13
- Angular Language service extension 0.900.5
![image](https://user-images.githubusercontent.com/7254476/149929233-40669c7e-b683-41ad-aa88-c53038016414.png)

To clarify: the issue is that VSCode hightlights as an error the components used even if bundling is correct (no problem whatsover when `ng serve` or `ng build`)

**Comment by MariaSolOs** [comment] 2022-10-15 17:23
Closing this as it isn't a problem with the VS extension.

**Closed by MariaSolOs** 2022-10-15 17:23 UTC
