### ISSUE TITLE
Can't add new line in html tags

### ISSUE THREAD

**Issue by awdorrin** [microsoft/vs-ng-language-service#56] opened 2022-12-01 12:32 UTC
Given html content such as the following:
```
1:  <ng-container matColumnDef="recommendationComment">
2:    <mat-header-cell *matHeaderCellDef mat-sort-header>Recommendation Comment </mat-header-cell>
3:    <mat-cell *matCellDef="let row"
4:              matTooltip="Click to Edit"
5:              (click)="recommendationCommentHandler(row)"
6:              [disabled]="disableCommentEdit(row)">
7:      {{row.recommendationComment}}
8:    </mat-cell>
9:  </ng-container>
```
When I navigate to the end of lines 3, 4, or 5, and press Enter, a new line is added then quickly removed.
The only way for me to add an attribute on a new line is to press space, start typing, move the cursor back in front of what I just started to type, then press 'enter' again.

I assume this is due to the auto-formatting/auto-completion logic - but I don't see any configuration options for this extension to change that behavior.

**Comment by MariaSolOs** [comment] 2022-12-05 19:56
I cannot reproduce the issue. For us to further investigate, please provide the following information:
- Which version of the extension are you using? With which version of VS?
- Do you have any other extensions installed?
- If possible, please provide a sample repo with the issue that we could use for testing.

**Comment by MariaSolOs** [comment] 2023-01-09 18:07
Closing because I couldn't reproduce the issue and we never heard back from the user.

**Closed by MariaSolOs** 2023-01-09 18:07 UTC
